### ISSUE TITLE
Make /say text appear at the top and overflow to the bottom

### ISSUE THREAD

**Issue by bpark08** [mmccaff/giphy-battle#15]

**Comment by mmccaff** [comment]
/say is still in the middle, but there are two new commands:

/saytop to say a message on the top.

/saybottom to say a message on the bottom.

Font-size is now viewport-based. 

Line-wrapping is disabled (maybe not a good idea, but dynamic font-size could accommodate for this if needed).

**Comment by bpark08** [comment]
👍
