### ISSUE TITLE
Store listening port in .env file (dotenv module?) instead of hardcoded 3000 and manually changing to 80 on prod

### ISSUE THREAD

**Issue by bpark08** [mmccaff/giphy-battle#6]

**Comment by mmccaff** [comment]
This is done. There is now a .sample_env under version control and the application relies on a .env existing (which is of course not under version control).

Current values in it look like this:
HTTP_PORT=3000
MONGO_URL=mongodb://localhost:27017/picroost

It uses the dotenv package for this.
